### ISSUE TITLE
java.lang.VerifyError when comparing floats with the literal 2.0

### ISSUE THREAD

**Issue by tbateson** [nicklauslittle/horseshoe-j#12]
```java
final Template template = new TemplateLoader().load("Test 1", "{{#value >= " + value + "}}Hello world!{{/}}");
final Map<String, Object> data = new HashMap<>();
data.put("value", value);
final Settings settings = new Settings();
final StringWriter writer = new StringWriter();
template.render(settings, data, writer);
Assert.assertEquals("Hello world!", writer.toString());
```
When `value` is anything other than exactly `2.0` this code above passes, however for the value `2.0` (but surprisingly not its equivalents such as `2`) this test fails! Other values such as 1.0, 2, 2.1, 3.0, and 4.0 all pass the above test.

```java
java.lang.VerifyError: (class: horseshoe/internal/dyn/Expression_259, method: evaluate signature: ([Lhorseshoe/internal/Identifier;Lhorseshoe/internal/PersistentStack;Lhorseshoe/Settings$ContextAccess;Lhorseshoe/internal/PersistentStack;)Ljava/lang/Object;) Expecting to find float on stack
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at horseshoe.internal.Expression.<init>(Expression.java:733)
	at horseshoe.TemplateLoader.loadTemplate(TemplateLoader.java:497)
	at horseshoe.TemplateLoader.load(TemplateLoader.java:358)
	at horseshoe.TemplateLoader.load(TemplateLoader.java:298)
	at horseshoe.TemplateLoader.load(TemplateLoader.java:262)
```
This was tested as of 517322e.

**Comment by nicklauslittle** [comment]
Should be fixed with commit 879fdf4.
